package local.plainconsole.fhirexper;

import ca.uhn.fhir.context.FhirContext;

import org.hl7.fhir.r4.model.Patient;

/**
 * Hello world For FHIR!
 * Reference : https://hapifhir.io/hapi-fhir/docs/introduction/introduction.html
 *
 */
public class App 
{
    public static void main( String[] args )
    {
        FhirContext ctxR4 = FhirContext.forR4();
        FhirConverter converter = new FhirConverter(ctxR4);

        // Data From: http://hapi.fhir.org/baseR4/Patient/dc69a791-9991-409f-8384-1260dead5439/_history/1
        String msgString = "{\"resourceType\":\"Patient\",\"id\":\"dc69a791-9991-409f-8384-1260dead5439\",\"meta\":{\"versionId\":\"1\",\"lastUpdated\":\"2020-03-24T20:30:03.389+00:00\",\"source\":\"#lUZaMlHVgRkhmSvK\",\"profile\":[\"http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient\"],\"tag\":[{\"system\":\"https://smarthealthit.org/tags\",\"code\":\"Covid19 synthetic population from Synthea\"}]},\"text\":{\"status\":\"generated\",\"div\":\"<div xmlns=\\\"http://www.w3.org/1999/xhtml\\\">Generated by <a href=\\\"https://github.com/synthetichealth/synthea\\\">Synthea</a>.Version identifier: 2177cffc\\n .   Person seed: 5241456023464700991  Population seed: 12345</div>\"},\"extension\":[{\"url\":\"http://hl7.org/fhir/us/core/StructureDefinition/us-core-race\",\"extension\":[{\"url\":\"ombCategory\",\"valueCoding\":{\"system\":\"urn:oid:2.16.840.1.113883.6.238\",\"code\":\"2106-3\",\"display\":\"White\"}},{\"url\":\"text\",\"valueString\":\"White\"}]},{\"url\":\"http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity\",\"extension\":[{\"url\":\"ombCategory\",\"valueCoding\":{\"system\":\"urn:oid:2.16.840.1.113883.6.238\",\"code\":\"2186-5\",\"display\":\"Not Hispanic or Latino\"}},{\"url\":\"text\",\"valueString\":\"Not Hispanic or Latino\"}]},{\"url\":\"http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName\",\"valueString\":\"Tess185 Conroy74\"},{\"url\":\"http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex\",\"valueCode\":\"F\"},{\"url\":\"http://hl7.org/fhir/StructureDefinition/patient-birthPlace\",\"valueAddress\":{\"city\":\"Springfield\",\"state\":\"Illinois\",\"country\":\"US\"}},{\"url\":\"http://synthetichealth.github.io/synthea/disability-adjusted-life-years\",\"valueDecimal\":0},{\"url\":\"http://synthetichealth.github.io/synthea/quality-adjusted-life-years\",\"valueDecimal\":12}],\"identifier\":[{\"system\":\"https://github.com/synthetichealth/synthea\",\"value\":\"cda866e6-c6df-48c7-82ae-7ae33435a6d0\"},{\"type\":{\"coding\":[{\"system\":\"http://terminology.hl7.org/CodeSystem/v2-0203\",\"code\":\"MR\",\"display\":\"Medical Record Number\"}],\"text\":\"Medical Record Number\"},\"system\":\"http://hospital.smarthealthit.org\",\"value\":\"cda866e6-c6df-48c7-82ae-7ae33435a6d0\"},{\"type\":{\"coding\":[{\"system\":\"http://terminology.hl7.org/CodeSystem/v2-0203\",\"code\":\"SS\",\"display\":\"Social Security Number\"}],\"text\":\"Social Security Number\"},\"system\":\"http://hl7.org/fhir/sid/us-ssn\",\"value\":\"999-51-9769\"}],\"name\":[{\"use\":\"official\",\"family\":\"Hayes766\",\"given\":[\"Gena729\"]}],\"telecom\":[{\"system\":\"phone\",\"value\":\"555-702-3172\",\"use\":\"home\"}],\"gender\":\"female\",\"birthDate\":\"2007-11-05\",\"address\":[{\"extension\":[{\"url\":\"http://hl7.org/fhir/StructureDefinition/geolocation\",\"extension\":[{\"url\":\"latitude\",\"valueDecimal\":41.81485938376962},{\"url\":\"longitude\",\"valueDecimal\":-87.54114050170077}]}],\"line\":[\"397 Wintheiser Fork\"],\"city\":\"Chicago\",\"state\":\"IL\",\"postalCode\":\"60007\",\"country\":\"US\"}],\"maritalStatus\":{\"coding\":[{\"system\":\"http://terminology.hl7.org/CodeSystem/v3-MaritalStatus\",\"code\":\"S\",\"display\":\"Never Married\"}],\"text\":\"Never Married\"},\"multipleBirthBoolean\":false,\"communication\":[{\"language\":{\"coding\":[{\"system\":\"urn:ietf:bcp:47\",\"code\":\"en-US\",\"display\":\"English\"}],\"text\":\"English\"}}]}";
        Patient patient = converter.ConvertToPatient(msgString);
        converter.ConvertToString(patient);
    }
}
